algoritmo "semnome"
// Função :
// Autor :
// Data : 10/3/2017
// Seção de Declarações 
var
piloto:caractere
distancia:real
tempo:real
velocidade:real

inicio
escreval("qual seu nome ?")
leia(piloto)
escreval("qual foi a distancia percorrida ?")
leia(distancia)
escreval("quanto tempo vc demorou ?")
leia (tempo)
velocidade<-distancia/tempo
escreval("o piloto ",piloto," foi a ",velocidade," Km/h")

fimalgoritmo
