algoritmo "semnome"
// Função :
// Autor :
// Data : 10/3/2017
// Seção de Declarações 
var
n1:real
n2:real
n3:real
n4:real
media:real
inicio
escreval("digite um numero")
leia(n1)
escreval("digite um numero")
leia(n2)
escreval("digite um numero")
leia(n3)
escreval("digite um numero")
leia(n4)
media<- (n1+n2+n3+n4) /4
escreval("a media dos quatro numeros e: ",media)
fimalgoritmo
