algoritmo "Exercicio 2"
// Função :para calcular a area de um cubo retangular
// Autor :
// Data : 9/3/2017
// Seção de Declarações 
var
altura: real
largura: real
base: real
area: real
inicio
escreval ("digite a altura do cubo")
leia (altura)
escreval ("digite a largura do cubo")
leia (largura)
escreval ("digite a base do cubo")
leia (base)

area<- altura*largura + altura*base + base*largura *2
escreval ("a area do cubo e",area)
fimalgoritmo
