algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2017
// Seção de Declarações 
var
nota1:real
nota2:real
media:real
inicio
escreval("digite a primeira nota")
leia(nota1)
escreval("digita a segunda nota")
leia(nota2)
media<-(nota1+nota2)/2
se media>=7 entao
   escreval("o aluno foi aprovado com media",media)
   senao
   Escreval("o aluno foi reprovado com media",media)
   fimse

fimalgoritmo
