algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2017
// Seção de Declarações 
var
v1:real
v2:real
v3:real
inicio
 leia(v1)
 leia(v2)
 leia(v3)
   se (v1>v2) e (v1>v3) entao
   escreval("o maior valor e o primeiro")
   senao
   se (v2>v1) e (v2>v3) entao
   escreval("o maior valor e o segundo")
   senao
    escreval("o maior valor e o terceiro")
    fimse
    fimse


fimalgoritmo
