algoritmo "semnome"
// Função :
// Autor :
// Data : 16/03/2017
// Seção de Declarações 
var
time1:inteiro
time2:inteiro
inicio
escreval("digite quantos pontos o time A fez :")
leia(time1)
escreval("digite quantos pontos o time B fez :")
leia(time2)
se time1>time2 entao
escreval("o time A e o vencedor")
senao
se time2>time1 entao
escreval("o time B e o vencedor")
senao
escreval("os times empataram")
fimse
fimse



fimalgoritmo
