algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2017
// Seção de Declarações 
var
idade:inteiro
anoAtual:inteiro
nascimento:inteiro
inicio
   escreval("digite o ano atual")
     leia(anoAtual)
   escreval("digite o ano de nascimento")
    leia(nascimento)
    idade<-anoAtual-nascimento
    se idade >=16  entao
    escreval("o cidadao pode votar")
    senao
    escreval("o cidadao nao pode votar")
    fimse
fimalgoritmo
